### PR TITLE
Update line 70 of .psm1 to allow for copying folders recursively

### PR DESCRIPTION
**Pull request by montereyharris**
Install-ModuleFromGithub was not copying Folders and contents of folders beyond the root of the repo. I fixed it by adding -Recurse to Copy-item

### CODE REVIEW

**Comment by jayvdb** [comment]
@montereyharris there is a conflict to be resolved.

**Comment by jayvdb** [comment]
ping @montereyharris - conflict needs to be resolved.

**Comment by montereyharris** [comment]
@jayvdb Resolved conflict. Changed code so it used -Recurse switch on copy.

**Comment by jayvdb** [comment]
@montereyharris this is closed??

**Comment by montereyharris** [comment]
Sorry that was an accident @jayvdb

**Comment by jayvdb** [comment]
Thx.  @ping @dfinke

**Pull request merged**
